- name: Pull Flask app image
  docker_image:
    name: wizfi/wisdom-flask
    source: pull

- name: Remove existing container
  docker_container:
    name: wisdom
    state: absent
    force_kill: true

- name: Run Flask container
  docker_container:
    name: wisdom
    image: wizfi/wisdom-flask
    state: started
    restart_policy: always
    ports:
      - "5000:5000"
    env:
      FLASK_ENV: production
