- name: Add Grafana APT key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana APT repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Start and enable Grafana service
  systemd:
    name: grafana-server
    enabled: yes
    state: started

- name: Download Node Exporter Dashboard JSON (1860)
  ansible.builtin.get_url:
    url: "https://grafana.com/api/dashboards/1860/revisions/27/download"
    dest: "/tmp/node_exporter_dashboard.json"
    mode: '0644'

- name: Upload dashboard to Grafana
  community.grafana.grafana_dashboard:
    grafana_url: "http://localhost:3000"
    grafana_user: admin
    grafana_password: "{{ grafana_admin_password }}"
    state: present
    path: "/tmp/node_exporter_dashboard.json"


- name: Download Flask App Dashboard JSON (12559)
  get_url:
    url: "https://grafana.com/api/dashboards/12559/revisions/1/download"
    dest: "/tmp/flask_dashboard.json"

- name: Upload Flask App Dashboard to Grafana
  community.grafana.grafana_dashboard:
    grafana_url: "http://localhost:3000"
    grafana_user: "admin"
    grafana_password: "{{ grafana_admin_password }}"
    state: present
    overwrite: true
    path: "/tmp/flask_dashboard.json"

- name: Download EC2 Dashboard JSON
  ansible.builtin.uri:
    url: "https://grafana.com/api/dashboards/11074/revisions/1/download"
    method: GET
    return_content: yes
  register: ec2_dashboard_json




- name: Save EC2 Dashboard JSON to File
  copy:
    content: "{{ ec2_dashboard_json.content }}"
    dest: /tmp/ec2_dashboard.json

- name: Upload EC2 Dashboard to Grafana
  community.grafana.grafana_dashboard:
    grafana_url: "http://localhost:3000"
    grafana_user: "admin"
    grafana_password: "{{ grafana_admin_password }}"
    state: present
    overwrite: true
    path: /tmp/ec2_dashboard.json

#  FLASK APP METRICS SETUP 

- name: Ensure Prometheus Flask Exporter is installed in Flask container
  ansible.builtin.shell: |
    docker exec wisdom pip install prometheus_flask_exporter

- name: Ensure /opt/flask directory exists
  ansible.builtin.file:
    path: /opt/flask
    state: directory
    mode: '0755'

- name: Debug Flask Dashboard JSON
  debug:
    var: flask_dashboard_json


- name: Copy updated Flask app with metrics support
  copy:
    src: ../flask/app_with_metrics.py
    dest: /opt/flask/app.py
  notify: Restart Flask App

- name: Update Prometheus config to scrape Flask app metrics
  blockinfile:
    path: /etc/prometheus/prometheus.yml
    marker: "# {mark} FLASK SCRAPE CONFIG"
    block: |
      - job_name: 'flask_app'
        static_configs:
          - targets: ['localhost:8000']
  notify: Restart Prometheus

- name: "Download Flask Dashboard JSON from Grafana Labs (ID: 9585)"
  ansible.builtin.uri:
    url: "https://grafana.com/api/dashboards/9585/revisions/latest/download"
    method: GET
    return_content: yes
  register: flask_dashboard_json_response


- name: Set fact for Flask dashboard JSON
  set_fact:
    flask_dashboard_json: "{{ flask_dashboard_json_response.content }}"


- name: Save Flask Dashboard JSON to File
  copy:
    content: "{{ flask_dashboard_json }}"
    dest: /etc/grafana/provisioning/dashboards/flask_dashboard.json
  become: yes


- name: Upload Flask Dashboard to Grafana
  community.grafana.grafana_dashboard:
    grafana_url: "http://localhost:3000"
    grafana_user: "admin"
    grafana_password: "{{ grafana_admin_password }}"
    state: present
    overwrite: true
    path: /tmp/flask_dashboard.json


