- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copy NGINX config
  copy:
    dest: /etc/nginx/sites-available/default
    content: |
      server {
          listen 80;
          server_name wizfi-devops.duckdns.org;

          location / {
              proxy_pass http://localhost:5000;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
          }
      }

- name: Restart NGINX
  systemd:
    name: nginx
    state: restarted
    enabled: yes
