---
- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Ensure NGINX is running
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Copy NGINX reverse proxy config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: '0644'

- name: Restart NGINX
  systemd:
    name: nginx
    state: restarted
