- name: Install Certbot & dependencies
  apt:
    name:
      - software-properties-common
      - certbot
      - python3-certbot-nginx
    state: present
    update_cache: yes

- name: Obtain SSL certificate
  command: >
    certbot --nginx --non-interactive --agree-tos
    -m shaibuwisdom@gmail.com
    -d wizfi-devops.duckdns.org

- name: Set up automatic renewal cron job
  cron:
    name: "Renew Let's Encrypt certificates"
    job: "certbot renew --quiet"
    state: present
    minute: "0"
    hour: "3"
