name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/wisdom-flask:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/wisdom-flask:latest

    - name: Copy SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Run Ansible Playbook
      run: |
        sudo apt-get update && sudo apt-get install -y ansible sshpass
        ansible-playbook -i "${{ secrets.EC2_HOST }}," ansible/site.yml \
          --private-key private_key.pem \
          -u ${{ secrets.EC2_USER }} \
          -e "ansible_python_interpreter=/usr/bin/python3"
