name: Deploy to Production

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Optional: Require build job to succeed first
    steps:
      - uses: actions/checkout@v4
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
      - uses: ansible/ansible-setup-action@v1
      - name: Run Ansible
        run: |
          ansible-playbook ansible/site.yml \
            --vault-password-file <(echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}") \
            -i ansible/inventory.ini \
            --private-key ~/.ssh/deploy_key \
            -u ubuntu