name: Build and Test Docker Image

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: wizfi/wisdom-flask:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Test Container
        run: |
          docker run -d -p 5000:5000 --name test wizfi/wisdom-flask:latest
          sleep 5
          docker exec test curl -s http://localhost:5000/metrics | grep flask_http_request_duration_seconds
          docker rm -f test